config/routes.rb
Rails.application.routes.draw do

  # 顧客側devise
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者側devise
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 顧客側ルーティング
  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'
    resources :items, only: [:index, :show]
    resources :genres, only: [:show]
    resources :cart_items do
      collection do
        delete 'destroy_all'
      end
    end
    resources :cart_items, only: [:index, :update, :destroy, :create]
    post '/orders/confirm' => 'orders#confirm', as: 'order_confirm'
    get '/orders/complete' => 'orders#complete', as: 'order_complete'
    resources :orders, only: [:new, :index, :create, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resource :customer do
      get 'my_page' => 'customers#show', as: 'my_page'
      get 'information/edit' => 'customers#edit', as: 'information_edit'
      patch 'information' => 'customers#update', as: 'information'
      get 'unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
      patch 'withdraw' => 'customers#withdraw', as: 'withdraw'
    end
  end

  # 管理者側ルーティング
  namespace :admin do
    root "homes#top"
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :genres, only: [:index, :edit, :update, :create]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:new, :show, :update]
    resources :order_details, only: [:update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer, optional: true
  
  def address_display
    '〒' + postal_code.to_s + ' ' + address.to_s + ' ' + name.to_s
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  # 小計
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :last_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true
  validates :telephone_number, presence: true, format: { with: /\A\d{10,11}\z/ }
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  belongs_to :genre
  
  # 商品単価(税込)
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy

  belongs_to :customer
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_for_payment: 0, deposit_confirmation: 1, production: 2, preparing_to_ship: 3, shipping_completed: 4 } 
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order#, optional: true
  # belongs_to :customer, optional: true
  belongs_to :item
  
  enum making_status: { cannot_be_manufactured: 0, waiting_for_production: 1, production: 2, completion_of_production: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  # ジャンル管理画面(一覧・追加を兼ねる)
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  # ジャンルデータ登録
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  # ジャンル編集画面
  def edit
    @genre = Genre.find(params[:id])
  end

  # ジャンルデータ更新
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all.page(params[:page]).per(10).order('created_at DESC')
    # @order = Order.find(params)
    @order_details = OrderDetail.where(order_id: params[:id])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  # 商品新規登録画面
  def new
    @item = Item.new
  end

  # 商品情報の新規登録
  def create
    @item = Item.new(item_params)
    if @item.save!
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  # 商品一覧
  def index
    @items = Item.page(params[:page]).per(10)
  end

  # 商品詳細画面
  def show
    @item = Item.find(params[:id])
  end

  # 商品編集画面
  def edit
    @item = Item.find(params[:id])
  end

  # 商品情報の更新
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active, :image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  # 管理者：注文詳細
  def show
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
  end
  
  # 管理者：注文ステータス更新
  def update
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
    if @order.update(order_params)
      @order_details.update_all(making_status: 0) if @order.status == "waiting_for_paymentcd"
      @order_details.update_all(making_status: 1) if @order.status == "deposit_confirmation"
    end
    redirect_to admin_order_path(@order)
  end
  
  private
  
  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected
  
  def after_sign_in_path_for(resources)
   admin_root_path
  end

  def after_sign_out_path_for(resources)
   new_admin_session_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<!--<h1>Admin::Genres#edit</h1>-->
<!--管理者：ジャンル編集画面-->
<div class="container">
  <div class="m-4">
    <h4 class="d-inline border border-secondary px-3">ジャンル編</h4>
  </div>

  <div>
    <%= form_with model: @genre, url: admin_genre_path(@genre) do |f| %>
      <%= f.label 'ジャンル名', class: "col-sm-2" %>
      <%= f.text_field :name, autofocus: true, class: "col-sm-2" %>
      <%= f.submit '変更を保存', class: "btn btn-success col-sm-2 ml-5" %>
    <% end %>
  </div>
</div>

app/views/admin/genres/index.html.erb
<!--<h1>Admin::Genres#index</h1>-->
<!--管理者：ジャンル管理画面(一覧・追加を兼ねる)-->
<div class="container">
  <div class="m-4">
    <h4 class="d-inline border border-secondary px-3">ジャンル一覧・追加</h4>
  </div>

  <div>
    <%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>
      <%= f.label 'ジャンル名', class: "col-sm-2" %>
      <%= f.text_field :name, autofocus: true, class: "col-sm-2", placeholder: "ジャンル名" %>
      <%= f.submit '新規登録', class: "btn btn-success col-sm-1 ml-5" %>
    <% end %>
  </div>

  <table class="table w-50 mt-5">
    <thead class="thead-light">
      <tr>
        <th class="col-sm-8">ジャンル</th>
        <th class="col-ms-2"></th>
      </tr>
    </thead>
    
    <tbody>
      <% @genres.each do |genre| %>
        <tr>
          <td><%= genre.name %></td>
          <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: 'btn btn-success' %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/admin/items/edit.html.erb
<!--<h1>Admin::Items#edit</h1>-->
<!--管理者：商品編集画面-->
<div class="container">
  <div class="m-4">
    <h4 class="d-inline border border-secondary px-3">商品編集</h4>
  </div>

  <%= form_with model: @item, url: admin_item_path(@item) do |f| %>
    <div class="form-group row justify-content-center">
      <%= f.label '商品画像', class: "col-sm-2 col-form-label" %>
      <div class="col-sm-6">
        <%= f.file_field :image, accept: "image/*" %>
      </div>
    </div>
    <div class="form-group row justify-content-center">
      <%= f.label '商品名', class: "col-sm-2 col-form-label" %>
      <div class="col-sm-6">
        <%= f.text_field :name, autofocus: true, class: "form-control col-sm-6" %>
      </div>
    </div>
    <div class="form-group row justify-content-center">
      <%= f.label '商品説明', class: "col-sm-2 col-form-label" %>
      <div class="col-sm-6">
        <%= f.text_area :introduction, class: "form-control col-sm-6" %>
      </div>
    </div>
    <div class="form-group row justify-content-center">
      <%= f.label 'ジャンル', class: "col-sm-2 col-form-label" %>
      <div class="col-sm-6">
        <%= f.collection_select :genre_id, Genre.all, :id, :name, {prompt: "--選択して下さい--"}, class: "form-control col-sm-6" %>
      </div>
    </div>
    <div class="form-group row justify-content-center">
      <%= f.label '税抜価格', class: "col-sm-1 col-form-label mx-5" %>
      <div class="col-sm-3">
        <%= f.text_field :price, class: "form-control col-sm-11 ml-5" %>
      </div>
      <div class="col-sm-4 text-left pt-3">円</div>
    </div>
    <div class="form-group row justify-content-center">
      <span class="col-sm-2 col-form-label">販売ステータス</span>
      <div class="col-sm-2">
        <%= f.radio_button :is_active, true %>
        <%= f.label :is_active, '販売中', value: true %>
      </div>
      <div class="col-sm-4">
        <%= f.radio_button :is_active, false %>
        <%= f.label :is_active, '販売停止中', value: false %>
      </div>
    </div>
    <p class="col">
      <%= f.submit '変更を保存', class: "btn btn-success mx-auto d-block" %>
    </p>
  <% end %>
</div>

app/views/admin/items/index.html.erb
<!--<h1>Admin::Items#index</h1>-->
<!--管理者：商品一覧-->
<div class="container">
  <div class="m-4">
    <h4 class="d-inline border border-secondary px-3">商品一覧</h4>
    <div class="text-right">
      <%= link_to image_tag("プラスアイコン.jpg", size: "50x50"), new_admin_item_path %>
    </div>
  </div>
  
  <div class="col-10 ml-5">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th class="col-1"><strong>商品ID</strong></th>
          <th class="col-4"><strong>商品名</strong></th>
          <th class="col-2"><strong>税抜価格</strong></th>
          <th class="col-3"><strong>ジャンル</strong></th>
          <th class="col-2"><strong>ステータス</strong></>
        </tr>
      </thead>
  
      <tbody>
        <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td>
            <ins>
            <%= link_to admin_item_path(item), class: "border_bottom text-dark" do %>
              <%= item.name %>
            <% end %>
            </ins>
          </td>
          <td><%= item.price.to_s(:delimited) %></td>
          <td><%= item.genre.name %></td>
          <td>
            <% if item.is_active == true %>
              <strong class="text-success">販売中</span>
            <% else item.is_active != true %>
              <strong class="text-black-50">販売停止中</span>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class="col-5">
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<!--<h1>Admin::Items#new</h1>-->
<!--管理者：商品新規登録画面-->
<div class="container">
  <div class="m-4">
    <h4 class="d-inline border border-secondary px-3">商品新規登録</h4>
  </div>

  <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
    <div class="form-group row justify-content-center">
      <%= f.label '商品画像', class: "col-sm-2 col-form-label" %>
      <div class="col-sm-6">
        <%= f.file_field :image, accept: "image/*" %>
      </div>
    </div>
    <div class="form-group row justify-content-center">
      <%= f.label '商品名', class: "col-sm-2 col-form-label" %>
      <div class="col-sm-6">
        <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "商品名" %>
      </div>
    </div>
    <div class="form-group row justify-content-center">
      <%= f.label '商品説明', class: "col-sm-2 col-form-label" %>
      <div class="col-sm-6">
        <%= f.text_area :introduction, class: "form-control", placeholder: "ここに説明文を記述します" %>
      </div>
    </div>
    <div class="form-group row justify-content-center">
      <%= f.label 'ジャンル', class: "col-sm-2 col-form-label" %>
      <div class="col-sm-6">
        <%= f.collection_select :genre_id, Genre.all, :id, :name, {prompt: "--選択して下さい--"}, class: "form-control" %>
      </div>
    </div>
    <div class="form-group row justify-content-center">
      <%= f.label '税抜価格', class: "col-sm-2 col-form-label" %>
      <div class="col-sm-6">
        <%= f.text_field :price, class: "form-control", placeholder: "税抜価格" %>
        <div>円</div>
      </div>
    </div>
    <div class="form-group row justify-content-center">
      <%= f.label '販売ステータス', class: "col-sm-2 col-form-label" %>
      <div class="col-sm-2">
        <%= f.radio_button :is_active, true %>
        <%= f.label :is_active, '販売中', value: true %>
      </div>
      <div class="col-sm-4">
        <%= f.radio_button :is_active, false %>
        <%= f.label :is_active, '販売停止中', value: false %>
      </div>
    </div>
    <p class="col">
      <%= f.submit '新規登録', class: "btn btn-success mx-auto d-block" %>
    </p>
  <% end %>
</div>

app/views/admin/items/show.html.erb
<!--<h1>Admin::Items#show</h1>-->
<!--管理者：商品詳細画面-->
<div class="container">
  <div class="m-4">
    <h4 class="d-inline border border-secondary px-3 mb-5">商品詳細</h4>
  </div>

  <div class="row mt-5">
    <div class="col-sm-4">
      <% if @item.image.attached? %>
        <%= image_tag @item.image, size: "300x230" %>
      <% else %>
        <%= image_tag 'default-image', size: "300x230" %>
      <% end %>
    </div>

    <div class="col-sm-8">
      <div class="row">
        <p class="col-sm-3">商品名</p>
        <div class="col-sm-9"><%= @item.name %></div>
      </div>
      <div class="row">
        <p class="col-sm-3">商品説明</p>
        <div class="col-sm-9"><%= @item.introduction %></div>
      </div>
      <div class="row">
        <p class="col-sm-3">ジャンル</p>
        <div class="col-sm-9"><%= @item.genre.name %></div>
      </div>
      <div class="row">
        <p class="col-sm-3">税込価格<br>(税抜価格)</p>
        <div class="col-sm-9">
          <%= (@item.price * 1.1).floor %>
          (<%= @item.price %>)円
        </div>
      </div>
      <div class="row">
        <p class="col-sm-3">販売ステータス</p>
        <p class="col-sm-9">
          <% if @item.is_active == true %>
            <strong class="text-success">販売中</span>
          <% else @item.is_active != true %>
            <strong class="text-black-50">販売停止中</span>
          <% end %>  
        </p>
      </div>
    </div>
  </div>
  <p class="row">
    <%= link_to '編集する', edit_admin_item_path(@item), class: "btn btn-success px-4 mx-auto d-block" %>
  </p>
</div>

app/views/admin/orders/show.html.erb
<!--<h1>Admin::Orders#show</h1>-->
<!--管理者：注文履歴詳細-->
<div class="container">
  <div class="m-4">
    <h4 class="d-inline border border-secondary px-3">注文履歴詳細</h4>
  </div>

  <div class="customer-content">
    <div class="row m-2">
      <h5 class="col-2"><strong>購入者</strong></h5>
      <div class="col-10">
        <%= link_to admin_customer_path(@order.customer_id), class: "text-dark border-bottom border-dark" do %>
          <%= @order.customer.first_name %><%= @order.customer.last_name %>
        <% end %>
      </div>
    </div>
    <div class="row m-2">
      <h5 class="col-2"><strong>注文日</strong></h5>
      <div class="col-10"><%= l @order.created_at, format: :short %></div>
    </div>
  </div>
  <div class="row m-2">
    <h5 class="col-2"><strong>配送先</strong></h5>
    <div class="col-10">
      〒<%= @order.postal_code %><%= @order.address %><br>
      <%= @order.name %>
    </div>
  </div>
  <div class="row m-2">
    <h5 class="col-2"><strong>支払方法</strong></h5>
    <div class="col-10">
      <%= @order.payment_method_i18n %>
    </div>
  </div>
  <div class="row m-2">
    <h5 class="col-2"><strong>注文ステータス</strong></h5>
    <div class="col-10">
      <%= form_for @order, url: admin_order_path do |f| %>
        <%= f.select :status, Order.statuses_i18n.invert %>
        <%= f.submit "更新", class: "btn btn-success ml-4 py-1" %>
      <% end %>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-8">
      <table class="table">
        <thead>
          <tr>
            <th class="col-3">商品名</th>
            <th class="col-2">単価(税込)</th>
            <th class="col-1">数量</th>
            <th class="col-2">小計</th>
            <th class="col-4">製作ステータス</th>
          </tr>
        </thead>
    
        <tbody>
          <% @order_details.each do |order_detail| %>
          <% @total = 0 %>
          <% @total += order_detail.item.with_tax_price %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= (order_detail.item.with_tax_price).to_s(:delimited) %></td>
            <td><%= order_detail.amount %></td>
            <td><%= order_detail.price.to_s(:delimited) %></td>
            <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id), method: :patch do |f| %>
            <td>
              <%= f.select :making_status, OrderDetail.making_statuses_i18n.invert, class: "ml-2" %>
              <%= f.submit "更新", class: "btn btn-success px-2 ml-5" %>
            </td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    
    <div class="col-1"></div>
    
    <div class="col-3">
      <table class="table table-borderless ">
        <tr>
          <th></th>
          <td></td>
        </tr>
        <tr>
          <th>商品合計</th>
          <td class="text-right"><%= (@order.total_payment - @order.shipping_cost).to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th>送料</th>
          <td class="text-right"><%= @order.shipping_cost %>円</td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td class="text-right"><strong><%= @order.total_payment.to_s(:delimited) %>円</strong></td>
        </tr>
      </table>
    </div>
  </div>
</div>