config/routes.rb
Rails.application.routes.draw do

  # 顧客側devise
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者側devise
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 顧客側ルーティング
  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'
    resources :items, only: [:index, :show]
    resources :genres, only: [:show]
    resources :cart_items do
      collection do
        delete 'destroy_all'
      end
    end
    resources :cart_items, only: [:index, :update, :destroy, :create]
    post '/orders/confirm' => 'orders#confirm', as: 'order_confirm'
    get '/orders/complete' => 'orders#complete', as: 'order_complete'
    resources :orders, only: [:new, :index, :create, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resource :customer do
      get 'my_page' => 'customers#show', as: 'my_page'
      get 'information/edit' => 'customers#edit', as: 'information_edit'
      patch 'information' => 'customers#update', as: 'information'
      get 'unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
      patch 'withdraw' => 'customers#withdraw', as: 'withdraw'
    end
  end

  # 管理者側ルーティング
  namespace :admin do
    root "homes#top"
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :genres, only: [:index, :edit, :update, :create]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:new, :show, :update]
    resources :order_details, only: [:update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer, optional: true
  
  def address_display
    '〒' + postal_code.to_s + ' ' + address.to_s + ' ' + name.to_s
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  # 小計
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :last_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true
  validates :telephone_number, presence: true, format: { with: /\A\d{10,11}\z/ }
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  belongs_to :genre
  
  # 商品単価(税込)
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy

  belongs_to :customer
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_for_payment: 0, deposit_confirmation: 1, production: 2, preparing_to_ship: 3, shipping_completed: 4 } 
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order#, optional: true
  # belongs_to :customer, optional: true
  belongs_to :item
  
  enum making_status: { cannot_be_manufactured: 0, waiting_for_production: 1, production: 2, completion_of_production: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  # ジャンル管理画面(一覧・追加を兼ねる)
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  # ジャンルデータ登録
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  # ジャンル編集画面
  def edit
    @genre = Genre.find(params[:id])
  end

  # ジャンルデータ更新
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all.page(params[:page]).per(10).order('created_at DESC')
    # @order = Order.find(params)
    @order_details = OrderDetail.where(order_id: params[:id])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  # 商品新規登録画面
  def new
    @item = Item.new
  end

  # 商品情報の新規登録
  def create
    @item = Item.new(item_params)
    if @item.save!
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  # 商品一覧
  def index
    @items = Item.page(params[:page]).per(10)
  end

  # 商品詳細画面
  def show
    @item = Item.find(params[:id])
  end

  # 商品編集画面
  def edit
    @item = Item.find(params[:id])
  end

  # 商品情報の更新
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active, :image)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_admin_header.html.erb
<li class="nav-item mr-3"><%= link_to '商品一覧', admin_items_path, class: "btn btn-outline-dark" %></li>
<li class="nav-item mr-3"><%= link_to '会員一覧', admin_customers_path, class: "btn btn-outline-dark" %></li>
<li class="nav-item mr-3"><%= link_to '注文履歴一覧', admin_root_path, class: "btn btn-outline-dark" %></li>
<li class="nav-item mr-3"><%= link_to 'ジャンル一覧', admin_genres_path, class: "btn btn-outline-dark" %></li>
<li class="nav-item mr-3"><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "btn btn-outline-dark" %></li>

app/views/layouts/_customer_header.html.erb
<li class="nav-item mr-3"><%= link_to 'マイページ', my_page_customer_path, class: "btn btn-outline-dark" %></li>
<li class="nav-item mr-3"><%= link_to '商品一覧', items_path, class: "btn btn-outline-dark" %></li>
<li class="nav-item mr-3"><%= link_to 'カート', cart_items_path, class: "btn btn-outline-dark" %></li>
<li class="nav-item mr-3"><%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: "btn btn-outline-dark" %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCafe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--管理者用ヘッダー：部分テンプレート引用部-->
    <header class="sticky-top">
    <nav class="navber navbar-expand-md bg-white pt-2">
      <div class="container">
        <div class="row">
          <ul class="nav navbar-nav mr-auto">
            <!--ショップロゴ-->
            <h2>
            <%= link_to root_path, class: "nav navber-nav  text-dark" do %>
                <%= image_tag 'パティシエ.jpg', :size => '45x45' %>Nagano Cake<%= image_tag 'ケーキ.jpg', :size => '45x45' %>
            <% end %>
            </h2>
          </ul>
          
          <ul class="nav navber-nav">
            <% if admin_signed_in? %>
              <%= render 'layouts/admin_header' %>
            <% elsif customer_signed_in? %>
              <%= render 'layouts/customer_header' %>
            <% else %>
              <li class="nav-item mr-3"><%= link_to 'About', about_path, class: "btn btn-outline-dark" %></li>
              <li class="nav-item mr-3"><%= link_to '商品一覧', items_path, class: "btn btn-outline-dark" %></li>
              <li class="nav-item mr-3"><%= link_to '新規登録', new_customer_registration_path, class: "btn btn-outline-dark" %></li>
              <li class="nav-item mr-3"><%= link_to 'ログイン', new_customer_session_path, class: "btn btn-outline-dark" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
</header>
    
    <%= yield %>
  </body>
</html>